AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - bin/*

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/LineLength:
  Max: 120

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
